site_name: Knowledge Distillation & Federated Learning

site_url: https://readingpapers.academy
repo_name: 'mwan0027/ReadingList'
repo_url: https://github.com/mwan0027/ReadingList.git

nav:
  - "Get Started": 'index.md'
  - 'Federated Learning':
      - 'IEEE':
          - '2020': 'FL/IEEE/ieee.md'
      - 'FD_ED_KD': 'FL/FL_KD/flkd.md'
      - 'Survey Paper Collection': 'FL/flsurvey.md'
  - 'Knowledge Distillation':
      - 'AAAI':
          - '2020': 'KD/AAAI/aaai2020.md'
      - 'ACL':
          - '2020': 'KD/ACL/acl2020.md'
      - 'EMNLP':
          - '2020': 'KD/EMNLP/emnlp2020.md'
      - 'ICLR':
          - '2020': 'KD/ICLR/iclr2020.md'
      - 'CVPR':
          - '2020': 'KD/CVPR/cvpr2020.md'
      - 'ICML':
          - '2020': 'KD/ICML/icml2020.md'          
      - 'NIPS':
          - '2020': 'KD/NIPS/nips2020.md'
          - '2018': 'KD/NIPS/nips2018.md'
          - '2017': 'KD/NIPS/nips2017.md'
      - 'Survey Paper Collection':
          - 'KD Survey(Gou et. al, 2020)': 'KD/KD_Survey/kdsurvey2020.md'
theme:
  material